/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const CustomerDetails = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'fullAddress' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'unitPriceAtOrder' : IDL.Nat,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customer' : CustomerDetails,
  'createdAt' : IDL.Int,
  'totalEstimate' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [ProductId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem), CustomerDetails], [OrderId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const CustomerDetails = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'fullAddress' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'unitPriceAtOrder' : IDL.Nat,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customer' : CustomerDetails,
    'createdAt' : IDL.Int,
    'totalEstimate' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [ProductId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), CustomerDetails],
        [OrderId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };