/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerDetails {
  'name' : string,
  'email' : string,
  'phone' : string,
  'fullAddress' : string,
}
export interface Order {
  'id' : OrderId,
  'customer' : CustomerDetails,
  'createdAt' : bigint,
  'totalEstimate' : bigint,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'unitPriceAtOrder' : bigint,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'image' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / **************************************
   * /    *             Product CRUD             *
   * /    ***************************************
   */
  'addProduct' : ActorMethod<[string, bigint, string, string], ProductId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  /**
   * / **************************************
   * /    *           Admin Order Review         *
   * /    ***************************************
   */
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / **************************************
   * /    *         User Profile Functions       *
   * /    ***************************************
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / **************************************
   * /    *            Order Placement           *
   * /    ***************************************
   */
  'placeOrder' : ActorMethod<[Array<OrderItem>, CustomerDetails], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];